### model
model_name_or_path: /largespace/tydata/code_data_results/finetuned_models/CodeQwen-1.5-7B/CodeQwen-1.5-7B_lora_sft_0716/CodeQwen-1.5-7B_lora_sft_0716_epoch_3

### method
stage: sft
do_train: true
finetuning_type: lora
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: Magicoder-Evol-Instruct-110K
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/CodeQwen-1.5-7B/lora/sft/0716/continue
logging_steps: 10
plot_loss: true
overwrite_output_dir: False
report_to: tensorboard
logging_dir: saves/CodeQwen-1.5-7B/lora/sft/0716/continue/logs/
print_param_status: false
save_strategy: epoch


### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: linear
warmup_ratio: 0.0
fp16: false
ddp_timeout: 180000000

### eval
val_size: 0
per_device_eval_batch_size: 1
evaluation_strategy: "no"