### model
model_name_or_path: /largespace/tydata/models-hf/CodeQwen1.5-7B

### method
stage: sft
do_train: true
finetuning_type: lora
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: Magicoder-OSS-Instruct-75K
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/CodeQwen-1.5-7B/lora/sft/0716/
logging_steps: 10
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard
logging_dir: saves/CodeQwen-1.5-7B/lora/sft/0716/logs/
print_param_status: false
save_strategy: epoch


### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: linear
warmup_ratio: 0.1
fp16: false
ddp_timeout: 180000000

### eval
val_size: 0
per_device_eval_batch_size: 1
evaluation_strategy: "no"