### model
model_name_or_path: /largespace/tydata/models-hf/deepseek-coder-6.7b-base

### method
stage: sft
do_train: true
finetuning_type: lora
deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: Code-Feedback-66K, Magicoder-Evol-Instruct-110K
mix_strategy: concat
template: deepseekcoder-our
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /largespace/tydata/code_data_results/finetuned_models/DeepSeekCoder-v1-6.7B/lora/sft/0724/
logging_steps: 1
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard
logging_dir: /largespace/tydata/code_data_results/finetuned_models/DeepSeekCoder-v1-6.7B/lora/sft/0724/logs/
print_param_status: true
save_strategy: epoch

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
fp16: false
ddp_timeout: 180000000

### eval
val_size: 0
per_device_eval_batch_size: 1
eval_strategy: "no"
